"""Canonical keybinding list: single source of truth for the
in-app help panel, the shortcuts browser, and the README.
Entries are (key, description, category)."""

KEY_CATEGORIES = ["Camera", "Visualization", "Analysis",
                  "Export", "Series", "Misc"]

KEYBINDINGS = [
    ("W / A / S / D", "Fly forward / left / back / right", "Camera"),
    ("Z / X", "Fly up / down", "Camera"),
    ("Q / E", "Roll counter-clockwise / clockwise", "Camera"),
    ("Mouse drag (LMB)", "Look around", "Camera"),
    ("Scroll", "Flight speed up / down", "Camera"),
    ("Ctrl+Scroll", "Optical zoom (FOV)", "Camera"),
    ("[ / ]", "Optical zoom in / out (FOV -/+ 5°)", "Camera"),
    ("R", "Auto-range color scale (Color slot in Composite)", "Visualization"),
    ("T", "Auto-range Lightness slot (Composite mode)", "Visualization"),
    ("L", "Toggle log / linear color scale", "Visualization"),
    ("- / =", "Widen / narrow color range", "Visualization"),
    ("C", "Cycle colormap", "Visualization"),
    (", / .", "Halve / double detail ceiling (subsample cap)", "Visualization"),
    ("P", "Save screenshot", "Export"),
    ("Ctrl+P", "Publication figure (colorbar + scale bar burned in)", "Export"),
    ("Ctrl+E", "Export sphere around center to HDF5 cutout", "Export"),
    ("Ctrl+Shift+E", "Export all analysis products as one ZIP", "Export"),
    ("Ctrl+M", "Export kernel-projected FITS map (aperture/center)", "Export"),
    ("F", "Toggle field filters (range cuts on any field)", "Analysis"),
    ("V", "Start / stop frame recording (movie export)", "Export"),
    ("Shift+Click", "Pick particle under cursor (opens inspector)", "Analysis"),
    ("I", "Toggle particle inspector", "Analysis"),
    ("G", "Toggle phase diagram (mass-weighted 2D histogram)", "Analysis"),
    ("J", "Toggle radial profile about the view center", "Analysis"),
    ("U", "Toggle region statistics (sphere about center)", "Analysis"),
    ("Shift+K", "Toggle power spectrum P(k) panel", "Analysis"),
    ("Shift+P", "Phase brush: select gas in phase space", "Analysis"),
    ("Shift+Z", "Slice plane normal / isosurface threshold cycle", "Visualization"),
    ("Shift+I", "Toggle isosurface panel (voxelize + marching cubes)", "Visualization"),
    ("Shift+S", "Split screen: off / left-right / top-bottom", "Visualization"),
    ("Shift+V", "Streamlines: compute / toggle visibility", "Visualization"),
    ("Shift+B", "Magnetic field arrows (MHD snapshots)", "Misc"),
    ("Shift+W", "Volume rendering: compute / toggle MIP", "Visualization"),
    ("Ctrl+R", "Regions panel: boolean multi-region scopes", "Analysis"),
    ("Tab (aperture)", "Cycle aperture shape (sphere/cyl/box/slab/cone/ellipsoid)", "Analysis"),
    ("M", "Aperture mode: click=center, scroll=size, M again=set", "Camera"),
    ("Shift+M", "Clear aperture (analysis back to global scope)", "Analysis"),
    ("F9", "Toggle science chrome (scale bar, status bar, axes)", "Visualization"),
    ("F10", "Toggle GPU frame-time profiler overlay", "Analysis"),
    ("1-9", "Fly to camera bookmark (eased)", "Camera"),
    ("Shift+1-9", "Save camera bookmark", "Camera"),
    ("N / Shift+N", "Look at view center / fly toward it", "Camera"),
    ("Y / Shift+Y", "Orbit the view center (reverse with Shift)", "Camera"),
    ("F2 / F3 / F4", "Snap view along +X / +Y / +Z (Shift: negative)", "Camera"),
    ("B / Shift+B", "Cycle star band forward / back", "Visualization"),
    ("O", "Toggle orbit-integration panel", "Analysis"),
    ("Shift+A", "Sightline mode: click 2 points (column densities)", "Analysis"),
    ("Shift+O", "Toggle star dust extinction", "Visualization"),
    ("K", "Toggle sink/star panel", "Visualization"),
    ("\\", "Toggle developer HUD", "Visualization"),
    ("Tab", "Hide / show all UI", "Visualization"),
    ("F1 or H", "Toggle this help", "Visualization"),
    ("Left / Right", "Previous / next snapshot (--series)", "Series"),
    ("Space", "Play / pause series playback", "Series"),
    ("Home / End", "First / last snapshot (--series)", "Series"),
    ("Ctrl+V", "Movie recorder panel", "Export"),
    ("Ctrl+Z / Ctrl+Shift+Z", "Undo / redo aperture-filter-mode", "Misc"),
    ("Ctrl+O / Ctrl+Q", "Open file dialog / quit", "Visualization"),
    ("Ctrl+Shift+D", "Toggle the right analysis dock", "Visualization"),
    ("Ctrl+H", "Halo list (requires --catalog)", "Analysis"),
    ("Esc", "Quit", "Visualization"),
]
