"""Canonical keybinding list: single source of truth for the in-app
help panel and the README controls table.
"""

KEYBINDINGS = [
    ("W / A / S / D", "Fly forward / left / back / right"),
    ("Z / X", "Fly up / down"),
    ("Q / E", "Roll counter-clockwise / clockwise"),
    ("Mouse drag (LMB)", "Look around"),
    ("Scroll", "Flight speed up / down"),
    ("Ctrl+Scroll", "Optical zoom (FOV)"),
    ("[ / ]", "Optical zoom in / out (FOV -/+ 5°)"),
    ("R", "Auto-range color scale (Color slot in Composite)"),
    ("T", "Auto-range Lightness slot (Composite mode)"),
    ("L", "Toggle log / linear color scale"),
    ("- / =", "Widen / narrow color range"),
    ("C", "Cycle colormap"),
    (", / .", "Halve / double detail ceiling (subsample cap)"),
    ("P", "Save screenshot"),
    ("Ctrl+P", "Publication figure (colorbar + scale bar burned in)"),
    ("Ctrl+E", "Export sphere around center to HDF5 cutout"),
    ("Ctrl+Shift+E", "Export all analysis products as one ZIP"),
    ("Ctrl+M", "Export kernel-projected FITS map (aperture/center)"),
    ("F", "Toggle field filters (range cuts on any field)"),
    ("V", "Start / stop frame recording (movie export)"),
    ("Shift+Click", "Pick particle under cursor (opens inspector)"),
    ("I", "Toggle particle inspector"),
    ("G", "Toggle phase diagram (mass-weighted 2D histogram)"),
    ("J", "Toggle radial profile about the view center"),
    ("U", "Toggle region statistics (sphere about center)"),
    ("Shift+K", "Toggle power spectrum P(k) panel"),
    ("Shift+Z", "Slice plane normal / isosurface threshold cycle"),
    ("Shift+I", "Toggle isosurface panel (voxelize + marching cubes)"),
    ("Shift+S", "Split screen: off / left-right / top-bottom"),
    ("Shift+V", "Streamlines: compute / toggle visibility"),
    ("Shift+B", "Magnetic field arrows (MHD snapshots)"),
    ("Shift+W", "Volume rendering: compute / toggle MIP"),
    ("Ctrl+R", "Regions panel: boolean multi-region scopes"),
    ("Tab (aperture)", "Cycle aperture shape (sphere/cyl/box/slab/cone/ellipsoid)"),
    ("M", "Aperture mode: click=center, scroll=size, M again=set"),
    ("Shift+M", "Clear aperture (analysis back to global scope)"),
    ("F9", "Toggle science chrome (scale bar, status bar, axes)"),
    ("F10", "Toggle GPU frame-time profiler overlay"),
    ("1-9", "Fly to camera bookmark (eased)"),
    ("Shift+1-9", "Save camera bookmark"),
    ("N / Shift+N", "Look at view center / fly toward it"),
    ("Y / Shift+Y", "Orbit the view center (reverse with Shift)"),
    ("F2 / F3 / F4", "Snap view along +X / +Y / +Z (Shift: negative)"),
    ("B / Shift+B", "Cycle star band forward / back"),
    ("O", "Toggle orbit-integration panel"),
    ("Shift+A", "Sightline mode: click 2 points (column densities)"),
    ("Shift+O", "Toggle star dust extinction"),
    ("K", "Toggle sink/star panel"),
    ("\\", "Toggle developer HUD"),
    ("Tab", "Hide / show all UI"),
    ("F1 or H", "Toggle this help"),
    ("Left / Right", "Previous / next snapshot (--series)"),
    ("Ctrl+O / Ctrl+Q", "Open file dialog / quit"),
    ("Esc", "Quit"),
]
